<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="10" total="19" passed="3" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-26T08:12:09Z" name="themomdesk" finished-at="2021-02-26T08:15:29Z" duration-ms="200754">
    <groups>
    </groups>
    <test started-at="2021-02-26T08:12:09Z" name="TheMomDesk Test" finished-at="2021-02-26T08:15:29Z" duration-ms="200754">
      <class name="com.themomsdesk.testCases.TC02_ContactPage">
        <test-method signature="testContactPage()[pri:0, instance:com.themomsdesk.testCases.TC02_ContactPage@5677323c]" started-at="2021-02-26T08:13:42Z" name="testContactPage" finished-at="2021-02-26T08:13:46Z" duration-ms="4269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testContactPage -->
      </class> <!-- com.themomsdesk.testCases.TC02_ContactPage -->
      <class name="com.themomsdesk.testCases.TC05_Blog">
        <test-method signature="testBlog()[pri:0, instance:com.themomsdesk.testCases.TC05_Blog@4d154ccd]" started-at="2021-02-26T08:14:08Z" name="testBlog" finished-at="2021-02-26T08:14:24Z" duration-ms="15375" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBlog -->
      </class> <!-- com.themomsdesk.testCases.TC05_Blog -->
      <class name="com.themomsdesk.testCases.TC04_Automation_Testing">
        <test-method signature="testAtutomationTesting()[pri:0, instance:com.themomsdesk.testCases.TC04_Automation_Testing@65c7a252]" started-at="2021-02-26T08:13:55Z" name="testAtutomationTesting" finished-at="2021-02-26T08:14:08Z" duration-ms="13248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAtutomationTesting -->
      </class> <!-- com.themomsdesk.testCases.TC04_Automation_Testing -->
      <class name="com.themomsdesk.testCases.TC06_ContactFormInvalidData">
        <test-method signature="contactFormInvalidData(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.themomsdesk.testCases.TC06_ContactFormInvalidData@229c6181]" started-at="2021-02-26T08:14:59Z" name="contactFormInvalidData" data-provider="ContactData" finished-at="2021-02-26T08:15:04Z" duration-ms="5078" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Biel]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[asdf.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.themomsdesk.testCases.TC06_ContactFormInvalidData.contactFormInvalidData(TC06_ContactFormInvalidData.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactFormInvalidData -->
        <test-method signature="contactFormInvalidData(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.themomsdesk.testCases.TC06_ContactFormInvalidData@229c6181]" started-at="2021-02-26T08:15:04Z" name="contactFormInvalidData" data-provider="ContactData" finished-at="2021-02-26T08:15:08Z" duration-ms="4171" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Biel]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Hi this is Biel]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.themomsdesk.testCases.TC06_ContactFormInvalidData.contactFormInvalidData(TC06_ContactFormInvalidData.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactFormInvalidData -->
        <test-method signature="contactFormInvalidData(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.themomsdesk.testCases.TC06_ContactFormInvalidData@229c6181]" started-at="2021-02-26T08:15:08Z" name="contactFormInvalidData" data-provider="ContactData" finished-at="2021-02-26T08:15:12Z" duration-ms="3908" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Hi this is Biel]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.themomsdesk.testCases.TC06_ContactFormInvalidData.contactFormInvalidData(TC06_ContactFormInvalidData.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactFormInvalidData -->
        <test-method signature="contactFormInvalidData(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.themomsdesk.testCases.TC06_ContactFormInvalidData@229c6181]" started-at="2021-02-26T08:15:12Z" name="contactFormInvalidData" data-provider="ContactData" finished-at="2021-02-26T08:15:17Z" duration-ms="4449" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raj]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.themomsdesk.testCases.TC06_ContactFormInvalidData.contactFormInvalidData(TC06_ContactFormInvalidData.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactFormInvalidData -->
      </class> <!-- com.themomsdesk.testCases.TC06_ContactFormInvalidData -->
      <class name="com.themomsdesk.testCases.TC01_CareerPage">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.themomsdesk.testCases.TC01_CareerPage@537f60bf]" started-at="2021-02-26T08:12:13Z" name="setup" finished-at="2021-02-26T08:13:36Z" duration-ms="83548" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testCareerText()[pri:0, instance:com.themomsdesk.testCases.TC01_CareerPage@537f60bf]" started-at="2021-02-26T08:13:37Z" name="testCareerText" finished-at="2021-02-26T08:13:41Z" duration-ms="4842" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.themomsdesk.testCases.TC01_CareerPage.testCareerText(TC01_CareerPage.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCareerText -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.themomsdesk.testCases.TC01_CareerPage@537f60bf]" started-at="2021-02-26T08:15:17Z" name="tearDown" finished-at="2021-02-26T08:15:29Z" duration-ms="12703" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.themomsdesk.testCases.TC01_CareerPage -->
      <class name="com.themomsdesk.testCases.TC03_ContactPageForm">
        <test-method signature="testContactPageForm()[pri:0, instance:com.themomsdesk.testCases.TC03_ContactPageForm@18df8434]" started-at="2021-02-26T08:13:46Z" name="testContactPageForm" finished-at="2021-02-26T08:13:55Z" duration-ms="8934" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.themomsdesk.testCases.TC03_ContactPageForm.testContactPageForm(TC03_ContactPageForm.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testContactPageForm -->
      </class> <!-- com.themomsdesk.testCases.TC03_ContactPageForm -->
    </test> <!-- TheMomDesk Test -->
  </suite> <!-- themomdesk -->
</testng-results>
